#!/bin/bash

####install python3####
yum -y install vim
yum groupinstall "Development tools"
yum install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel
mkdir -p /root/soft/python3
if [ ! -e /root/soft/python3/Python-3.6.1.tgz ];then
	wget https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tgz -O /root/soft/python3/Python-3.6.1.tgz
fi
mkdir -p /usr/local/python3
tar -zxvf /root/soft/python3/Python-3.6.1.tgz -C /root/soft/python3
while [ $? -ne 0 ]
do
	rm -rf tar -zxvf /root/soft/python3/Python-3.6.1*
	wget https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tgz -O /root/soft/python3/Python-3.6.1.tgz
	tar -zxvf /root/soft/python3/Python-3.6.1.tgz -C /root/soft/python3
done

cd /root/soft/python3/Python-3.6.1
./configure --prefix=/usr/local/python3
make
make install
if [ ! -e /usr/bin/python3 ];then
ln -s /usr/local/python3/bin/python3 /usr/bin/python3
fi
grep -E /usr/local/python3/bin /root/.bash_profile
if [ $? -ne 0 ];then
	sed -i 's/PATH=$PATH:$HOME\/bin/PATH=$PATH:$HOME\/bin:\/usr\/local\/python3\/bin/g' ~/.bash_profile
	source ~/.bash_profile
fi
if [ ! -e /usr/bin/pip3 ]; then
ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3
fi


####install httpd####
yum -y install httpd
release=`cat /etc/centos-release | awk '{print $4}'`
release_num=`echo ${release:0:1}`
if [ $release_num -eq '7' ];then
	systemctl start httpd
	systemctl enable httpd
else 
	service start httpd
	chkconfig httpd on
fi

####install django####
pip3 install django